#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoQLDD.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDD")]
	public partial class dbQLDinhDuongDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBENHNHAN(BENHNHAN instance);
    partial void UpdateBENHNHAN(BENHNHAN instance);
    partial void DeleteBENHNHAN(BENHNHAN instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertCTTD(CTTD instance);
    partial void UpdateCTTD(CTTD instance);
    partial void DeleteCTTD(CTTD instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHUCDON(THUCDON instance);
    partial void UpdateTHUCDON(THUCDON instance);
    partial void DeleteTHUCDON(THUCDON instance);
    partial void InsertTHUCPHAM(THUCPHAM instance);
    partial void UpdateTHUCPHAM(THUCPHAM instance);
    partial void DeleteTHUCPHAM(THUCPHAM instance);
    #endregion
		
		public dbQLDinhDuongDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLDDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDinhDuongDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDinhDuongDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDinhDuongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDinhDuongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BENHNHAN> BENHNHANs
		{
			get
			{
				return this.GetTable<BENHNHAN>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<CTTD> CTTDs
		{
			get
			{
				return this.GetTable<CTTD>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THUCDON> THUCDONs
		{
			get
			{
				return this.GetTable<THUCDON>();
			}
		}
		
		public System.Data.Linq.Table<THUCPHAM> THUCPHAMs
		{
			get
			{
				return this.GetTable<THUCPHAM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BENHNHAN")]
	public partial class BENHNHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MABENHNHAN;
		
		private string _HO;
		
		private string _TEN;
		
		private string _GIOITINH;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private System.Nullable<double> _CHIEUCAO;
		
		private System.Nullable<double> _CANNANG;
		
		private System.Nullable<double> _CALO;
		
		private System.Nullable<double> _NUOC;
		
		private System.Nullable<double> _BMI;
		
		private string _IDTAIKHOAN;
		
		private EntitySet<THUCDON> _THUCDONs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABENHNHANChanging(string value);
    partial void OnMABENHNHANChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnCHIEUCAOChanging(System.Nullable<double> value);
    partial void OnCHIEUCAOChanged();
    partial void OnCANNANGChanging(System.Nullable<double> value);
    partial void OnCANNANGChanged();
    partial void OnCALOChanging(System.Nullable<double> value);
    partial void OnCALOChanged();
    partial void OnNUOCChanging(System.Nullable<double> value);
    partial void OnNUOCChanged();
    partial void OnBMIChanging(System.Nullable<double> value);
    partial void OnBMIChanged();
    partial void OnIDTAIKHOANChanging(string value);
    partial void OnIDTAIKHOANChanged();
    #endregion
		
		public BENHNHAN()
		{
			this._THUCDONs = new EntitySet<THUCDON>(new Action<THUCDON>(this.attach_THUCDONs), new Action<THUCDON>(this.detach_THUCDONs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABENHNHAN", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABENHNHAN
		{
			get
			{
				return this._MABENHNHAN;
			}
			set
			{
				if ((this._MABENHNHAN != value))
				{
					this.OnMABENHNHANChanging(value);
					this.SendPropertyChanging();
					this._MABENHNHAN = value;
					this.SendPropertyChanged("MABENHNHAN");
					this.OnMABENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(20)")]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(10)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIEUCAO", DbType="Float")]
		public System.Nullable<double> CHIEUCAO
		{
			get
			{
				return this._CHIEUCAO;
			}
			set
			{
				if ((this._CHIEUCAO != value))
				{
					this.OnCHIEUCAOChanging(value);
					this.SendPropertyChanging();
					this._CHIEUCAO = value;
					this.SendPropertyChanged("CHIEUCAO");
					this.OnCHIEUCAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANNANG", DbType="Float")]
		public System.Nullable<double> CANNANG
		{
			get
			{
				return this._CANNANG;
			}
			set
			{
				if ((this._CANNANG != value))
				{
					this.OnCANNANGChanging(value);
					this.SendPropertyChanging();
					this._CANNANG = value;
					this.SendPropertyChanged("CANNANG");
					this.OnCANNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALO", DbType="Float")]
		public System.Nullable<double> CALO
		{
			get
			{
				return this._CALO;
			}
			set
			{
				if ((this._CALO != value))
				{
					this.OnCALOChanging(value);
					this.SendPropertyChanging();
					this._CALO = value;
					this.SendPropertyChanged("CALO");
					this.OnCALOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUOC", DbType="Float")]
		public System.Nullable<double> NUOC
		{
			get
			{
				return this._NUOC;
			}
			set
			{
				if ((this._NUOC != value))
				{
					this.OnNUOCChanging(value);
					this.SendPropertyChanging();
					this._NUOC = value;
					this.SendPropertyChanged("NUOC");
					this.OnNUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Float")]
		public System.Nullable<double> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTAIKHOAN", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string IDTAIKHOAN
		{
			get
			{
				return this._IDTAIKHOAN;
			}
			set
			{
				if ((this._IDTAIKHOAN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._IDTAIKHOAN = value;
					this.SendPropertyChanged("IDTAIKHOAN");
					this.OnIDTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENHNHAN_THUCDON", Storage="_THUCDONs", ThisKey="MABENHNHAN", OtherKey="MABENHNHAN")]
		public EntitySet<THUCDON> THUCDONs
		{
			get
			{
				return this._THUCDONs;
			}
			set
			{
				this._THUCDONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_BENHNHAN", Storage="_TAIKHOAN", ThisKey="IDTAIKHOAN", OtherKey="IDTAIKHOAN", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.BENHNHANs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.BENHNHANs.Add(this);
						this._IDTAIKHOAN = value.IDTAIKHOAN;
					}
					else
					{
						this._IDTAIKHOAN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.BENHNHAN = this;
		}
		
		private void detach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.BENHNHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACHUCVU;
		
		private string _TENCHUCVU;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCVUChanging(int value);
    partial void OnMACHUCVUChanged();
    partial void OnTENCHUCVUChanging(string value);
    partial void OnTENCHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(25)")]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this.OnTENCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCVU = value;
					this.SendPropertyChanged("TENCHUCVU");
					this.OnTENCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="MACHUCVU", OtherKey="MACHUCVU")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTTD")]
	public partial class CTTD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUCDON;
		
		private string _MATHUCPHAM;
		
		private string _TENTHUCPHAM;
		
		private System.Nullable<double> _KHOILUONG;
		
		private System.Nullable<double> _DAM;
		
		private System.Nullable<double> _BEO;
		
		private System.Nullable<double> _XO;
		
		private System.Nullable<double> _CALO;
		
		private EntityRef<THUCDON> _THUCDON;
		
		private EntityRef<THUCPHAM> _THUCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUCDONChanging(string value);
    partial void OnMATHUCDONChanged();
    partial void OnMATHUCPHAMChanging(string value);
    partial void OnMATHUCPHAMChanged();
    partial void OnTENTHUCPHAMChanging(string value);
    partial void OnTENTHUCPHAMChanged();
    partial void OnKHOILUONGChanging(System.Nullable<double> value);
    partial void OnKHOILUONGChanged();
    partial void OnDAMChanging(System.Nullable<double> value);
    partial void OnDAMChanged();
    partial void OnBEOChanging(System.Nullable<double> value);
    partial void OnBEOChanged();
    partial void OnXOChanging(System.Nullable<double> value);
    partial void OnXOChanged();
    partial void OnCALOChanging(System.Nullable<double> value);
    partial void OnCALOChanged();
    #endregion
		
		public CTTD()
		{
			this._THUCDON = default(EntityRef<THUCDON>);
			this._THUCPHAM = default(EntityRef<THUCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCDON", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCDON
		{
			get
			{
				return this._MATHUCDON;
			}
			set
			{
				if ((this._MATHUCDON != value))
				{
					if (this._THUCDON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUCDONChanging(value);
					this.SendPropertyChanging();
					this._MATHUCDON = value;
					this.SendPropertyChanged("MATHUCDON");
					this.OnMATHUCDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCPHAM", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCPHAM
		{
			get
			{
				return this._MATHUCPHAM;
			}
			set
			{
				if ((this._MATHUCPHAM != value))
				{
					if (this._THUCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUCPHAMChanging(value);
					this.SendPropertyChanging();
					this._MATHUCPHAM = value;
					this.SendPropertyChanged("MATHUCPHAM");
					this.OnMATHUCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUCPHAM", DbType="NVarChar(30)")]
		public string TENTHUCPHAM
		{
			get
			{
				return this._TENTHUCPHAM;
			}
			set
			{
				if ((this._TENTHUCPHAM != value))
				{
					this.OnTENTHUCPHAMChanging(value);
					this.SendPropertyChanging();
					this._TENTHUCPHAM = value;
					this.SendPropertyChanged("TENTHUCPHAM");
					this.OnTENTHUCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOILUONG", DbType="Float")]
		public System.Nullable<double> KHOILUONG
		{
			get
			{
				return this._KHOILUONG;
			}
			set
			{
				if ((this._KHOILUONG != value))
				{
					this.OnKHOILUONGChanging(value);
					this.SendPropertyChanging();
					this._KHOILUONG = value;
					this.SendPropertyChanged("KHOILUONG");
					this.OnKHOILUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAM", DbType="Float")]
		public System.Nullable<double> DAM
		{
			get
			{
				return this._DAM;
			}
			set
			{
				if ((this._DAM != value))
				{
					this.OnDAMChanging(value);
					this.SendPropertyChanging();
					this._DAM = value;
					this.SendPropertyChanged("DAM");
					this.OnDAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEO", DbType="Float")]
		public System.Nullable<double> BEO
		{
			get
			{
				return this._BEO;
			}
			set
			{
				if ((this._BEO != value))
				{
					this.OnBEOChanging(value);
					this.SendPropertyChanging();
					this._BEO = value;
					this.SendPropertyChanged("BEO");
					this.OnBEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XO", DbType="Float")]
		public System.Nullable<double> XO
		{
			get
			{
				return this._XO;
			}
			set
			{
				if ((this._XO != value))
				{
					this.OnXOChanging(value);
					this.SendPropertyChanging();
					this._XO = value;
					this.SendPropertyChanged("XO");
					this.OnXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALO", DbType="Float")]
		public System.Nullable<double> CALO
		{
			get
			{
				return this._CALO;
			}
			set
			{
				if ((this._CALO != value))
				{
					this.OnCALOChanging(value);
					this.SendPropertyChanging();
					this._CALO = value;
					this.SendPropertyChanged("CALO");
					this.OnCALOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCDON_CTTD", Storage="_THUCDON", ThisKey="MATHUCDON", OtherKey="MATHUCDON", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public THUCDON THUCDON
		{
			get
			{
				return this._THUCDON.Entity;
			}
			set
			{
				THUCDON previousValue = this._THUCDON.Entity;
				if (((previousValue != value) 
							|| (this._THUCDON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCDON.Entity = null;
						previousValue.CTTDs.Remove(this);
					}
					this._THUCDON.Entity = value;
					if ((value != null))
					{
						value.CTTDs.Add(this);
						this._MATHUCDON = value.MATHUCDON;
					}
					else
					{
						this._MATHUCDON = default(string);
					}
					this.SendPropertyChanged("THUCDON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CTTD", Storage="_THUCPHAM", ThisKey="MATHUCPHAM", OtherKey="MATHUCPHAM", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public THUCPHAM THUCPHAM
		{
			get
			{
				return this._THUCPHAM.Entity;
			}
			set
			{
				THUCPHAM previousValue = this._THUCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._THUCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUCPHAM.Entity = null;
						previousValue.CTTDs.Remove(this);
					}
					this._THUCPHAM.Entity = value;
					if ((value != null))
					{
						value.CTTDs.Add(this);
						this._MATHUCPHAM = value.MATHUCPHAM;
					}
					else
					{
						this._MATHUCPHAM = default(string);
					}
					this.SendPropertyChanged("THUCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDTAIKHOAN;
		
		private string _MATKHAU;
		
		private string _HO;
		
		private string _TEN;
		
		private string _GIOITINH;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private System.Nullable<int> _SDT;
		
		private string _EMAIL;
		
		private System.Nullable<int> _MACHUCVU;
		
		private EntitySet<BENHNHAN> _BENHNHANs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTAIKHOANChanging(string value);
    partial void OnIDTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnMACHUCVUChanging(System.Nullable<int> value);
    partial void OnMACHUCVUChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._BENHNHANs = new EntitySet<BENHNHAN>(new Action<BENHNHAN>(this.attach_BENHNHANs), new Action<BENHNHAN>(this.detach_BENHNHANs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTAIKHOAN", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDTAIKHOAN
		{
			get
			{
				return this._IDTAIKHOAN;
			}
			set
			{
				if ((this._IDTAIKHOAN != value))
				{
					this.OnIDTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._IDTAIKHOAN = value;
					this.SendPropertyChanged("IDTAIKHOAN");
					this.OnIDTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(20)")]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(10)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="Char(40)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="Int")]
		public System.Nullable<int> MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_BENHNHAN", Storage="_BENHNHANs", ThisKey="IDTAIKHOAN", OtherKey="IDTAIKHOAN")]
		public EntitySet<BENHNHAN> BENHNHANs
		{
			get
			{
				return this._BENHNHANs;
			}
			set
			{
				this._BENHNHANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_TAIKHOAN", Storage="_CHUCVU", ThisKey="MACHUCVU", OtherKey="MACHUCVU", IsForeignKey=true, DeleteRule="CASCADE")]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._MACHUCVU = value.MACHUCVU;
					}
					else
					{
						this._MACHUCVU = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BENHNHANs(BENHNHAN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_BENHNHANs(BENHNHAN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCDON")]
	public partial class THUCDON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUCDON;
		
		private string _BUOI;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private string _HOBENHNHAN;
		
		private string _TENBENHNHAN;
		
		private string _MABENHNHAN;
		
		private EntitySet<CTTD> _CTTDs;
		
		private EntityRef<BENHNHAN> _BENHNHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUCDONChanging(string value);
    partial void OnMATHUCDONChanged();
    partial void OnBUOIChanging(string value);
    partial void OnBUOIChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnHOBENHNHANChanging(string value);
    partial void OnHOBENHNHANChanged();
    partial void OnTENBENHNHANChanging(string value);
    partial void OnTENBENHNHANChanged();
    partial void OnMABENHNHANChanging(string value);
    partial void OnMABENHNHANChanged();
    #endregion
		
		public THUCDON()
		{
			this._CTTDs = new EntitySet<CTTD>(new Action<CTTD>(this.attach_CTTDs), new Action<CTTD>(this.detach_CTTDs));
			this._BENHNHAN = default(EntityRef<BENHNHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCDON", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCDON
		{
			get
			{
				return this._MATHUCDON;
			}
			set
			{
				if ((this._MATHUCDON != value))
				{
					this.OnMATHUCDONChanging(value);
					this.SendPropertyChanging();
					this._MATHUCDON = value;
					this.SendPropertyChanged("MATHUCDON");
					this.OnMATHUCDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUOI", DbType="NVarChar(15)")]
		public string BUOI
		{
			get
			{
				return this._BUOI;
			}
			set
			{
				if ((this._BUOI != value))
				{
					this.OnBUOIChanging(value);
					this.SendPropertyChanging();
					this._BUOI = value;
					this.SendPropertyChanged("BUOI");
					this.OnBUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBENHNHAN", DbType="NVarChar(20)")]
		public string HOBENHNHAN
		{
			get
			{
				return this._HOBENHNHAN;
			}
			set
			{
				if ((this._HOBENHNHAN != value))
				{
					this.OnHOBENHNHANChanging(value);
					this.SendPropertyChanging();
					this._HOBENHNHAN = value;
					this.SendPropertyChanged("HOBENHNHAN");
					this.OnHOBENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBENHNHAN", DbType="NVarChar(10)")]
		public string TENBENHNHAN
		{
			get
			{
				return this._TENBENHNHAN;
			}
			set
			{
				if ((this._TENBENHNHAN != value))
				{
					this.OnTENBENHNHANChanging(value);
					this.SendPropertyChanging();
					this._TENBENHNHAN = value;
					this.SendPropertyChanged("TENBENHNHAN");
					this.OnTENBENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABENHNHAN", DbType="Char(5)")]
		public string MABENHNHAN
		{
			get
			{
				return this._MABENHNHAN;
			}
			set
			{
				if ((this._MABENHNHAN != value))
				{
					if (this._BENHNHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABENHNHANChanging(value);
					this.SendPropertyChanging();
					this._MABENHNHAN = value;
					this.SendPropertyChanged("MABENHNHAN");
					this.OnMABENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCDON_CTTD", Storage="_CTTDs", ThisKey="MATHUCDON", OtherKey="MATHUCDON")]
		public EntitySet<CTTD> CTTDs
		{
			get
			{
				return this._CTTDs;
			}
			set
			{
				this._CTTDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENHNHAN_THUCDON", Storage="_BENHNHAN", ThisKey="MABENHNHAN", OtherKey="MABENHNHAN", IsForeignKey=true, DeleteRule="CASCADE")]
		public BENHNHAN BENHNHAN
		{
			get
			{
				return this._BENHNHAN.Entity;
			}
			set
			{
				BENHNHAN previousValue = this._BENHNHAN.Entity;
				if (((previousValue != value) 
							|| (this._BENHNHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BENHNHAN.Entity = null;
						previousValue.THUCDONs.Remove(this);
					}
					this._BENHNHAN.Entity = value;
					if ((value != null))
					{
						value.THUCDONs.Add(this);
						this._MABENHNHAN = value.MABENHNHAN;
					}
					else
					{
						this._MABENHNHAN = default(string);
					}
					this.SendPropertyChanged("BENHNHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTTDs(CTTD entity)
		{
			this.SendPropertyChanging();
			entity.THUCDON = this;
		}
		
		private void detach_CTTDs(CTTD entity)
		{
			this.SendPropertyChanging();
			entity.THUCDON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCPHAM")]
	public partial class THUCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUCPHAM;
		
		private string _TENTHUCPHAM;
		
		private System.Nullable<double> _DAM;
		
		private System.Nullable<double> _BEO;
		
		private System.Nullable<double> _XO;
		
		private System.Nullable<double> _CALO;
		
		private EntitySet<CTTD> _CTTDs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUCPHAMChanging(string value);
    partial void OnMATHUCPHAMChanged();
    partial void OnTENTHUCPHAMChanging(string value);
    partial void OnTENTHUCPHAMChanged();
    partial void OnDAMChanging(System.Nullable<double> value);
    partial void OnDAMChanged();
    partial void OnBEOChanging(System.Nullable<double> value);
    partial void OnBEOChanged();
    partial void OnXOChanging(System.Nullable<double> value);
    partial void OnXOChanged();
    partial void OnCALOChanging(System.Nullable<double> value);
    partial void OnCALOChanged();
    #endregion
		
		public THUCPHAM()
		{
			this._CTTDs = new EntitySet<CTTD>(new Action<CTTD>(this.attach_CTTDs), new Action<CTTD>(this.detach_CTTDs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCPHAM", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCPHAM
		{
			get
			{
				return this._MATHUCPHAM;
			}
			set
			{
				if ((this._MATHUCPHAM != value))
				{
					this.OnMATHUCPHAMChanging(value);
					this.SendPropertyChanging();
					this._MATHUCPHAM = value;
					this.SendPropertyChanged("MATHUCPHAM");
					this.OnMATHUCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUCPHAM", DbType="NVarChar(30)")]
		public string TENTHUCPHAM
		{
			get
			{
				return this._TENTHUCPHAM;
			}
			set
			{
				if ((this._TENTHUCPHAM != value))
				{
					this.OnTENTHUCPHAMChanging(value);
					this.SendPropertyChanging();
					this._TENTHUCPHAM = value;
					this.SendPropertyChanged("TENTHUCPHAM");
					this.OnTENTHUCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAM", DbType="Float")]
		public System.Nullable<double> DAM
		{
			get
			{
				return this._DAM;
			}
			set
			{
				if ((this._DAM != value))
				{
					this.OnDAMChanging(value);
					this.SendPropertyChanging();
					this._DAM = value;
					this.SendPropertyChanged("DAM");
					this.OnDAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEO", DbType="Float")]
		public System.Nullable<double> BEO
		{
			get
			{
				return this._BEO;
			}
			set
			{
				if ((this._BEO != value))
				{
					this.OnBEOChanging(value);
					this.SendPropertyChanging();
					this._BEO = value;
					this.SendPropertyChanged("BEO");
					this.OnBEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XO", DbType="Float")]
		public System.Nullable<double> XO
		{
			get
			{
				return this._XO;
			}
			set
			{
				if ((this._XO != value))
				{
					this.OnXOChanging(value);
					this.SendPropertyChanging();
					this._XO = value;
					this.SendPropertyChanged("XO");
					this.OnXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALO", DbType="Float")]
		public System.Nullable<double> CALO
		{
			get
			{
				return this._CALO;
			}
			set
			{
				if ((this._CALO != value))
				{
					this.OnCALOChanging(value);
					this.SendPropertyChanging();
					this._CALO = value;
					this.SendPropertyChanged("CALO");
					this.OnCALOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUCPHAM_CTTD", Storage="_CTTDs", ThisKey="MATHUCPHAM", OtherKey="MATHUCPHAM")]
		public EntitySet<CTTD> CTTDs
		{
			get
			{
				return this._CTTDs;
			}
			set
			{
				this._CTTDs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTTDs(CTTD entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = this;
		}
		
		private void detach_CTTDs(CTTD entity)
		{
			this.SendPropertyChanging();
			entity.THUCPHAM = null;
		}
	}
}
#pragma warning restore 1591
